### ISSUE TITLE
Launching qemu with id-block fails

### ISSUE THREAD

**Issue by agal19** [AMDESE/sev-guest#13]
Hello,

I'm having trouble launching an SNP-VM with qemu when I pass the id-block argument. My snp-related qemu arguments are the following:
`-machine memory-encryption=sev0,vmport=off -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1,id-block=$(ID_BLOCK),id-auth=$(ID_AUTH),policy=0xb0000,auth-key-enabled=off`

The ID_BLOCK and the ID_AUTH point to base64 encoded blobs that I have generated with the sev-host-identity tool as:
`./sev-host-identity -b ./ec384.pem -d [measurement] -i ./id-block.bin -a ./auth-info.bin -p 0xb0000`

I got the measurement from the report I generated for the same VM when I launched it without the id-block argument.

The error I get is the following:
`qemu-system-x86_64: sev_snp_launch_finish: SNP_LAUNCH_FINISH ret=-5 fw_error=22 'Invalid parameter'`

**Comment by jlarrew** [comment]
Hello agal19,

To check my understanding, are the shell variables being created to contain the contents of the id-block.bin and id-auth.bin files?

For example:
```
ID_BLOCK=$(cat id-block.bin)
ID_AUTH=$(cat id-auth.bin)
```

Sincerely,
Jesse

**Comment by agal19** [comment]
Hi Jesse, yes exactly.

**Comment by jlarrew** [comment]
Hi agal19,

There appears to be a bug in the SNP firmware where it always fails the launch if an authority key is not supplied in the authentication information structure. A workaround is to generate a second EC keypair (using the NIST P-384 curve) to act as the authority key and pass that to sev-host-identity as well:

```
openssl genpkey -algorithm EC -outform PEM -out auth.pem -pkeyopt ec_paramgen_curve:P-384
./sev-host-identity -b ./ec384.pem ./auth.pem -d [measurement] -i ./id-block.bin -a ./auth-info.bin -p 0xb0000
```

Let me know if this works for you. Thanks!

Sincerely,
Jesse

**Comment by agal19** [comment]
Hi Jesse,

Yes, that worked. Thanks a lot!

Best,
Anna
