### ISSUE TITLE
attestation example

### ISSUE THREAD

**Issue by khushboo-dfn** [AMDESE/sev-guest#2]
We noticed that on Oct 13, an example for SEV-SNP attestation was checked in but it got reverted after a couple of hours. Is there an ETA for when this example will be checked in again?
![Screenshot from 2021-10-12 22-13-21](https://user-images.githubusercontent.com/50337148/137964513-22ea55c5-daf2-4eb2-b286-6edbb6ea9c87.png)

**Comment by jlarrew** [comment]
Sorry for the false start. It took longer than expected to get legal approval to post this code, but it's "street legal" now. ;)

**Comment by jlarrew** [comment]
Now that the repository is publilc, I'll go ahead and close this issue.
