### ISSUE TITLE
Missing data / link

### ISSUE THREAD

**Issue by msnitish** [AMDESE/sev-guest#3]
In this link : [Guest VM Setup](https://github.com/AMDESE/sev-guest#example-setup) , when clicked on[ 'Guest Owner Setup'](https://github.com/AMDESE/sev-guest/blob/main/docs/guest-owner-setup.md), the data/link is missing which is supposed to explain how to setup a guest VM.

**Comment by jlarrew** [comment]
Hi Nitish,

I'm currently updating the install instructions for the Guest Owner's infrastructure. I'll update this issue when it's posted. Thanks!

Sincerely,
Jesse

**Comment by jlarrew** [comment]
Hi Nitish,

I've added the Guest Owner setup instructions [here](https://github.com/AMDESE/sev-guest/blob/main/docs/guest-owner-setup.md). Thanks for the report!

Sincerely,
Jesse
