### ISSUE TITLE
What does "multipass" mean?

### ISSUE THREAD

**Issue by StanPlatinum** [AMDESE/sev-guest#6]
Dear all,

Could anyone give a definition of "multipass"? I saw it at https://github.com/AMDESE/sev-guest/blob/main/attestation/cryptsetup-initramfs/get-disk-key#L7 and in some graphs, but having no clue what it is...

Thanks!

**Comment by jlarrew** [comment]
Hi StanPlatinum,

Multipass is a VM orchestrator that allows you to run and manage VM instances with a container-like interface.

https://multipass.run/

I have a local build that I have modded to start VMs in SEV-SNP mode, so you might see some references to it in code comments. Nothing in this repository is dependent on Multipass, though. Any method of starting VMs that supports cloud-init can run the examples in this repository.

Sincerely,
Jesse
